development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: webblog3_development
  pool: 5
  username: root
  password: 
#socket: /tmp/mysql.sock
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: webblog3_test
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2 
  encoding: utf8
  reconnect: false 
  database: webblog3
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

